export enum SocketEventNames {
  createRoom = "create",
  joinRoom = "join",
  startGame = "start-game",
  getRooms = "get-rooms",
  turnOverCard = "turn-over-card",
  changeTurn = "change-turn",
  requestTimeOut = "request-time-out",
  requestTurnChange = "requestTurnChange",
  onError = "exception",
  onRoomCreated = "room-created",
  onPlayerJoined = "player-joined",
  onPlayerLeft = "player-left",
  onGameStarted = "game-started",
  onCardTurnedOver = "card-turned-over",
  onCardSelected = "card-selected",
  onGetRooms = "rooms",
  onTurnChanged = "turn-changed",
}
